/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateOrder: typeof import('./src/components/CreateOrder.vue')['default']
    DiagnosticReportDetail: typeof import('./src/components/DiagnosticReportDetail.vue')['default']
    DiagnosticReportList: typeof import('./src/components/DiagnosticReportList.vue')['default']
    ImagingList: typeof import('./src/components/ImagingList.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    OrderDetail: typeof import('./src/components/OrderDetail.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    PatientDetail: typeof import('./src/components/PatientDetail.vue')['default']
    PatientList: typeof import('./src/components/PatientList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
