/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventHistory: typeof import('./src/components/EventHistory.vue')['default']
    EventReportInfo: typeof import('./src/components/EventReportInfo.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    ReconciliationPanel: typeof import('./src/components/ReconciliationPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SummaryBar: typeof import('./src/components/SummaryBar.vue')['default']
    WorkitemDetail: typeof import('./src/components/WorkitemDetail.vue')['default']
    WorklistTable: typeof import('./src/components/WorklistTable.vue')['default']
  }
}
