/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventDetailPanel: typeof import('./src/components/EventDetailPanel.vue')['default']
    EventFilterBar: typeof import('./src/components/EventFilterBar.vue')['default']
    EventReportInfo: typeof import('./src/components/EventReportInfo.vue')['default']
    EventsTable: typeof import('./src/components/EventsTable.vue')['default']
    EventSummaryBar: typeof import('./src/components/EventSummaryBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionsPanel: typeof import('./src/components/SubscriptionsPanel.vue')['default']
  }
}
